modified:   README.md 	renamed:    mkinitrd/mkinitrd -> mkinitrd 	deleted:    mkinitrd/README.md 	deleted:    pls-install/main.cpp 	deleted:    pls-install/main.hpp

diff --git a/mkinitrd b/mkinitrd
--- a/mkinitrd
+++ b/mkinitrd
@@ -8,8 +8,53 @@
 #                              #
 ################################
 
-echo "mkinitrd, Version 0.01"
-echo "(gpl)2020 PocketNES Software, debajo GPLv3\n"
+init(){
+	echo "* Inicializando tempdir at $1..."
+	cd $1
+	mkdir -p $1/workdir
+	mkdir -p $1/initramfs
+	cp $init $1/workdir
+	cp $busybox $1/workdir
+}
+
+create_fs(){
+	echo "* Creando sistema de archivos:"
+	for i in bin dev sbin usr/bin usr/sbin; do
+		echo "	# initramfs/$i"
+		mkdir -p initramfs/$i
+	done
+	mv workdir/busybox initramfs/bin
+	mv workdir/init initramfs
+	mknod initramfs/dev/console c 5 1
+	mknod initramfs/dev/tty c 5 0
+	mknod initramfs/dev/null c 1 3
+}
+
+create_ar(){
+	echo "* Creando"
+	cd initramfs
+	find . | cpio -o --format=newc > ../initramfs.cpio
+	cd ..
+	case $compression in
+		"gzip")
+			gzip initramfs.cpio
+			;;
+		"bzip2")
+			bzip2 initramfs.cpio
+			;;
+		"xz")
+			xz --check=crc32 initramfs.cpio
+			;;
+	esac
+}
+
+echo "mkinitrd, Version 0.10"
+echo "(c) 2020 PocketNES Software, debajo GPLv3\n"
+
+if [ $(id -u) -ne 0 ]; then
+	echo "Error: No eres root. Tienes que ser root para utilizar esta herramienta"
+	exit 1
+fi
 
 #Chequea todos los parametros
 while [ $# -gt 0 ]; do
@@ -53,7 +98,11 @@ if [ "$busybox" = "" ]; then
 	exit 2
 elif [ "$init" = "" ]; then
 	echo "Error: --init es requirido."
-	exit 3
+	exit 2
 fi
 
+tempdir=$(mktemp -dt pls-XXXXXX)
 
+init $tempdir
+create_fs
+create_ar
