modified:   pls-install

diff --git a/pls-install b/pls-install
--- a/pls-install
+++ b/pls-install
@@ -1,4 +1,9 @@
 #!/bin/sh
+if [ $(id -u) -ne 0 ]; then
+	echo "Error: Usted no es root. Necesita ser root para poder usar $0"
+	exit 1
+fi
+
 case $1 in
 	"install" | "instalar")
 		shift
